server:
  port: 8081

spring:
  application:
    name: respuesta-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5433/respuestas
    username: postgres
    password: intihaku4523
  jpa:
    show-sql: true
    hibernate:
      dialect: PostgreSQLDialect
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true