server:
  port: 8083

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: pregunta-service
          uri: lb://PREGUNTA-SERVICE
          predicates:
            - Path=/preguntas/**
        - id: respuesta-service
          uri: lb://RESPUESTA-SERVICE
          predicates:
            - Path=/respuestas/**
        - id: calculoNotas-service
          uri: lb://CALCULONOTAS-SERVICE
          predicates:
            - Path=/notas/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true