server:
  port: 8080

spring:
  application:
    name: pregunta-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/preguntas
    username: postgres
    password: intihaku4523
  jpa:
    show-sql: true
    hibernate:
      dialect: PostgreSQLDialect
      ddl-auto: create