server:
  port: 8082

spring:
  application:
    name: calculoNotas-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/notas
    username: postgres
    password: intihaku4523
  jpa:
    show-sql: true
    hibernate:
      dialect: PostgreSQLDialect
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true